package main

import (
	"sort"
	"strings"

	"singbox-launcher/core/config/registry"
)

// renderIndex — оглавление: версия контракта и ядра, три ступени конвейера,
// список схем со ссылками, суб-схемы, коды.
//
// Страница английская целиком (решение владельца): сгенерированный каталог
// двуязычным не держим — русские тексты реестра читает UI, а не документация.
func renderIndex(raw *rawRegistry, reg *registry.Registry, schemes []string) string {
	var b strings.Builder
	b.WriteString("# Node contract: schemes, fields, codes\n\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("These pages are generated from the `contract/registry/` registry by " +
		"`go generate ./contract/...`, and CI checks them against the registry on every PR. " +
		"Hand edits are overwritten by the next run: change the registry instead.\n\n")

	t := &table{head: []string{"", "Version"}}
	t.add("Contract (`contract/VERSION`)", code(raw.version))
	t.add("Core (`body.core`)", coreVersions(reg, schemes))
	t.render(&b)

	b.WriteString(indexIntro())

	b.WriteString("## Pipeline\n\n")
	b.WriteString("Every input — a share URI, sing-box or Xray JSON, a wg-conf, a hand-written " +
		"body — goes through the same three stages in both apps:\n\n")
	b.WriteString("1. **mapper** — translates the dialect into a canonical body path using " +
		"`uri.*.maps_to` and the registry aliases. It checks no values and fills in no " +
		"defaults. Its structural translations are listed under **Replacements** on each " +
		"scheme page.\n")
	b.WriteString("2. **sanitizer** — runs the registry `body` sections: type, enum, format, " +
		"`allowed_for`/`forbidden_for`, `conflicts`/`requires`. Every drop or coercion is " +
		"recorded in `warnings[]` ([codes](warnings.md)).\n")
	b.WriteString("3. **emitter** — serializes in `body.order`; there is no per-scheme " +
		"branching in the code.\n\n")
	b.WriteString("The normative text is [`contract/docs/PARSING_PRINCIPLES.md` §8](../PARSING_PRINCIPLES.md).\n\n")

	b.WriteString("## Schemes\n\n")
	// Колонка `extension` снята: она пуста почти у всех строк, а «поддержано
	// одним проектом» — редкая заметка, которой место рядом со схемой, а не
	// отдельным столбцом прочерков.
	st := &table{head: []string{
		"Scheme", "sing-box `type`", "`kind`", "Accepted from", "Link form",
	}}
	for _, scheme := range schemes {
		p := raw.protocols[scheme]
		if p == nil {
			continue
		}
		name := "[`" + scheme + "`](protocols/" + schemeFileName(scheme) + ")"
		if p.Extension != nil && *p.Extension != "" {
			name += " — " + extWord(*p.Extension)
		}
		link := "no"
		if p.URI != nil {
			link = "yes"
		}
		st.add(name, code(p.SingboxType), code(p.Kind), sourceWords(p.Sources), link)
	}
	st.render(&b)

	b.WriteString("## Shared sub-schemas\n\n")
	sub := &table{head: []string{"Sub-schema", "What is inside"}}
	sub.add("[`tls`](protocols/_tls.md)", "TLS, uTLS, REALITY, ECH — link parameters and body fields")
	sub.add("[`transports`](protocols/_transports.md)", "transport variants by `transport.type`")
	sub.add("[`multiplex`](protocols/_multiplex.md)", "stream multiplexing")
	sub.add("[`dialer`](protocols/_dialer.md)", "common dialer fields, inlined flat")
	sub.render(&b)

	b.WriteString("## Warning codes\n\n")
	b.WriteString("[`warnings.md`](warnings.md) is the code dictionary: severity, what happened, " +
		"why it happens, what you can do, and a reverse index of which field of which scheme " +
		"raises each code.\n\n")

	// Лимиты — имя и канон, без `note`: там лежит переписка разработчиков о
	// расхождениях сторон (по-русски), а не объяснение для читателя.
	b.WriteString("## Limits\n\n")
	b.WriteString("The canonical value; an app may currently enforce a lower one.\n\n")
	lt := &table{head: []string{"Limit", "Value"}}
	limits := reg.Limits()
	names := make([]string, 0, len(limits))
	for k := range limits {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, n := range names {
		lt.add(code(n), scalar(limits[n].Value))
	}
	lt.render(&b)

	return b.String()
}

// coreVersions — версии ядра из `body.core` схем. Обычно она одна на весь
// реестр; если схемы разъехались, страница показывает это, а не прячет.
func coreVersions(reg *registry.Registry, schemes []string) string {
	seen := map[string]bool{}
	for _, s := range schemes {
		if body, ok := reg.Body(s); ok && body.Core != "" {
			seen[body.Core] = true
		}
	}
	return codeList(sortedKeys(seen))
}
