package main

import (
	"sort"
	"strconv"
	"strings"

	"singbox-launcher/core/config/registry"
)

// subPageFile — страница общей суб-схемы, на которую ссылается `ref` в теле.
// Имя файла начинается с подчёркивания: страница не принадлежит ни одной
// схеме, она общая.
var subPageFile = map[string]string{
	"tls":        "_tls.md",
	"transports": "_transports.md",
	"multiplex":  "_multiplex.md",
	"dialer":     "_dialer.md",
}

// renderScheme строит страницу одной схемы. Страница обязана быть
// САМОДОСТАТОЧНОЙ: человек, открывший её из-за одного узла подписки, не
// должен обходить четыре общие суб-схемы, чтобы понять, что с его узлом
// может случиться.
//
// Порядок разделов — от входа к последствиям:
//
//	шапка → How to read this page → Link parameters → Body fields →
//	Diagnosed problems → Replacements → Degradation
//
// Самодостаточность держится на двух вещах: словарь ссылки РАЗВЁРНУТ (общие
// параметры TLS и транспортов печатаются здесь, а не только на _tls.md /
// _transports.md), и поля тела ссылочных блоков развёрнуты тоже — иначе
// «Maps to» вело бы на адрес, которого на странице нет. Обе стороны связаны
// якорями в обе стороны: параметр → поле и поле → параметр.
//
// Страница английская целиком (решение владельца): `desc_ru`, `text_ru` и
// `impl` в неё не попадают.
func renderScheme(raw *rawRegistry, scheme string, body *registry.BodySchema) string {
	p := raw.protocols[scheme]
	var b strings.Builder

	title := scheme
	if p != nil && p.SingboxType != "" && p.SingboxType != scheme {
		title = scheme + " → " + p.SingboxType
	}
	b.WriteString("# " + title + "\n\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("[← index](../index.md) · [diagnosed problems](../warnings.md)\n\n")

	// Словарь ссылки считается один раз: он нужен и разделу «Link parameters»,
	// и обратным ссылкам у полей тела («этот параметр сюда и кладут»).
	params := schemeLinkParams(raw, scheme, p, body)

	renderSchemeHeader(&b, p, body)
	b.WriteString(schemeIntro(scheme, len(params) > 0, hasSharedGroup(params)))
	renderURIList(&b, raw, scheme, p, params)
	renderBodyList(&b, scheme, body, params)
	renderSchemeWarnings(&b, raw, scheme, body)
	renderReplacements(&b, raw, scheme, p)
	renderDegradation(&b, scheme, body)
	return b.String()
}

// renderSchemeHeader — шапка страницы: человеческая фраза и под ней таблица
// метаданных.
//
// Фраза отвечает на вопрос «что это вообще такое и откуда берётся», таблица —
// та же справка для разработчика (решение владельца: таблицу оставить).
// Пустых строк в таблице нет: «`extension`: —» не сообщает ничего.
func renderSchemeHeader(b *strings.Builder, p *rawProtocol, body *registry.BodySchema) {
	if p == nil {
		b.WriteString("No registry entry for this scheme.\n\n")
		return
	}

	line := "`" + p.Scheme + "` — " + kindWord(p.Kind)
	if p.SingboxType != "" {
		line += ", sing-box type `" + p.SingboxType + "`"
	}
	line += "."
	if names := aliasNames(p.Aliases); len(names) > 0 {
		line += " Also written as " + codeList(names) + "."
	}
	if src := sourceWords(p.Sources); src != "" {
		line += " Accepted from: " + src + "."
	}
	if p.Extension != nil && *p.Extension != "" {
		line += " " + extWord(*p.Extension) + "."
	}
	b.WriteString(line + "\n\n")

	// Вторая строка — мелкие сведения, которые нужны при сверке, но не при
	// первом чтении.
	var small []string
	if body != nil && body.Core != "" {
		small = append(small, "Schema checked against core `"+body.Core+"`")
	}
	if p.URI != nil && p.URI.Fragment != "" {
		small = append(small, "the link fragment (`#…`) is the node `"+p.URI.Fragment+"`")
	}
	if len(small) > 0 {
		b.WriteString("<sub>" + strings.Join(small, " · ") + "</sub>\n\n")
	}

	t := &table{head: []string{"Field", "Value"}}
	t.add("`scheme`", code(p.Scheme))
	t.add("`singbox_type`", code(p.SingboxType))
	t.add("`kind`", code(p.Kind))
	if len(p.Aliases) > 0 {
		t.add("`aliases`", codeList(aliasNames(p.Aliases)))
	}
	if len(p.Sources) > 0 {
		t.add("`sources`", codeList(p.Sources))
	}
	if p.Extension != nil && *p.Extension != "" {
		t.add("`extension`", code(*p.Extension))
	}
	if body != nil && body.Core != "" {
		t.add("Core the schema was checked against", code(body.Core))
	}
	if body != nil && body.OnCoreUnsupported != nil {
		var need []string
		if body.MinCore != "" {
			need = append(need, "core ≥ "+code(body.MinCore))
		}
		if body.BuildTag != "" {
			need = append(need, "build tag "+code(body.BuildTag))
		}
		t.add("Core requirement", strings.Join(need, ", ")+
			"; on a core that lacks it the node is dropped at build: "+code(body.OnCoreUnsupported.Code))
	}
	if body != nil && len(body.Levels) > 0 {
		t.add("Protocol levels (node label, ascending)", codeList(body.Levels))
	}
	if body != nil && body.ExitCapableWhen != nil {
		t.add("Exit to the internet (Direction pools)", "only"+conditionPhrase(body.ExitCapableWhen))
	}
	if body != nil {
		for _, rel := range body.Relations {
			if rel.Kind != "ordered" {
				continue
			}
			line := "must not decrease: " + codeList(rel.Paths)
			switch rel.Action {
			case "drop":
				line += "; otherwise all of them are removed"
			case "drop_node":
				line += "; otherwise the node is dropped"
			}
			t.add("Field order", line+": "+code(rel.Code))
		}
	}
	if p.URI != nil && p.URI.Fragment != "" {
		t.add("URI fragment", code(p.URI.Fragment))
	}
	t.render(b)
}

// kindWord — `kind` реестра словами. Слово `endpoint` в sing-box значит
// «не outbound, а интерфейс», и без пояснения читается как синоним.
func kindWord(kind string) string {
	switch kind {
	case "outbound":
		return "an outbound"
	case "endpoint":
		return "an endpoint (a tunnel interface, not a plain outbound)"
	case "group":
		return "an outbound group"
	case "":
		return "a scheme"
	}
	return "a " + kind
}

// sourceWords — `sources` реестра человеческими именами входов.
func sourceWords(sources []string) string {
	names := map[string]string{
		"uri":     "share link",
		"singbox": "sing-box JSON",
		"xray":    "Xray JSON",
		"wgconf":  "WireGuard .conf",
		"amnezia": "AmneziaWG .conf",
	}
	out := make([]string, 0, len(sources))
	for _, s := range sources {
		if n, ok := names[s]; ok {
			out = append(out, n)
		} else {
			out = append(out, code(s))
		}
	}
	return strings.Join(out, ", ")
}

// extWord — `extension`/`ext` реестра: пометка «поддержано пока одним
// проектом». Внутреннее `mobile`/`desktop` читателю ничего не говорит.
func extWord(ext string) string {
	switch ext {
	case "mobile":
		return "Supported by LxBox only"
	case "desktop":
		return "Supported by the desktop launcher only"
	}
	return "Supported by `" + ext + "` only"
}

// renderURIList — словарь ссылки, сгруппированный по подзаголовкам. У каждого
// параметра сразу видно, куда он ложится в теле (якорной ссылкой на само поле
// ниже по странице) и что будет с негодным значением: правило поля тела по
// адресу maps_to ищется тут же, чтобы человек не прыгал между разделами.
func renderURIList(b *strings.Builder, raw *rawRegistry, scheme string, p *rawProtocol, groups []linkGroup) {
	b.WriteString("## Link parameters\n\n")
	if p == nil || p.URI == nil {
		b.WriteString("The scheme has no link form: it comes from sing-box JSON only.\n\n")
		return
	}
	if len(groups) == 0 {
		b.WriteString("The scheme carries no link parameters.\n\n")
		return
	}

	lead := "Everything a link of this scheme can carry"
	if hasSharedGroup(groups) {
		lead += ", including the TLS and transport parameters shared with other schemes"
	}
	lead += ". **Maps to** points at the body field the value lands in; **If invalid** is that " +
		"field's own rule.\n\n"
	b.WriteString(lead)

	for _, g := range groups {
		b.WriteString("### " + g.title + "\n\n")
		if g.note != "" {
			b.WriteString(g.note + "\n\n")
		}
		l := &list{b: b}
		for _, item := range g.items {
			writeLinkItem(l, raw, scheme, item)
		}
		b.WriteString("\n")
	}
}

// writeLinkItem печатает один параметр ссылки на странице схемы.
func writeLinkItem(l *list, raw *rawRegistry, scheme string, item linkParam) {
	p := item.param
	l.item(anchorTag(item.anchor)+"**`"+item.name+"`**", p.DescEn)
	if p.Ext != "" {
		l.attr(extWord(p.Ext))
	}

	writeParamAttrs(l, p)

	// Куда ложится в теле и что будет с негодным значением.
	switch {
	case p.DropAlways:
		l.attr("Maps to: nothing — the parameter is read and then deliberately dropped")
	case len(item.bodyPaths) > 0:
		l.attr("Maps to: " + bodyPathLinks(raw, scheme, item.bodyPaths))
	}
	if rule := linkOutcome(raw, scheme, item); rule != "" {
		l.attr(rule)
	}
}

// writeParamAttrs — тип, допустимые значения и дефолт параметра ссылки: общая
// часть для страницы схемы и для страниц общих суб-схем.
func writeParamAttrs(l *list, p *uriParam) {
	if names := aliasNames(p.Aliases); len(names) > 0 {
		l.attr("Also spelled: " + codeList(names))
	}

	typ := paramTypeWord(p.Type)
	if len(p.Values) > 0 {
		typ = strings.TrimSpace(typ + ": " + codeList(p.Values))
	}
	if p.Allowlist != "" {
		typ = strings.TrimSpace(typ + " (allowlist `" + p.Allowlist + "`)")
	}
	if p.Meaning != "" && typ == "" {
		typ = code(p.Meaning)
	}
	if p.Validation != "" {
		typ = strings.TrimSpace(typ + " — " + p.Validation)
	}
	def := ""
	if s := scalar(p.Default); s != "" {
		def = "Default: " + s
	}
	if typ != "" {
		l.attr("Type: "+typ, def)
	} else {
		l.attr(def)
	}
}

// paramTypeWord разворачивает внутренние имена типов реестра. `alias_enum` —
// жаргон реестра: снаружи это закрытый список, который вдобавок понимает чужие
// написания.
func paramTypeWord(t string) string {
	switch t {
	case "alias_enum":
		return "enum (other spellings of the same value are accepted)"
	case "ignored":
		return "read and ignored"
	}
	return t
}

// bodyPathLinks — адреса в теле якорными ссылками на поля этой же страницы.
// Поля, которого на странице нет (ключ внутри карты заголовков), ссылкой не
// становится: якорь вёл бы в пустоту.
func bodyPathLinks(raw *rawRegistry, scheme string, paths []string) string {
	out := make([]string, 0, len(paths))
	for _, path := range paths {
		if _, resolved := resolveBodyField(raw, scheme, path); resolved == path {
			out = append(out, "[`"+path+"`](#"+bodyAnchor(path)+")")
			continue
		}
		out = append(out, code(path))
	}
	return strings.Join(out, ", ")
}

// linkOutcome — что будет с негодным значением параметра. Собственное правило
// параметра ссылки приоритетно; если его нет, берётся правило ПОЛЯ ТЕЛА, в
// которое параметр отображается: сам параметр решений о значении не принимает,
// этим занят санитайзер.
func linkOutcome(raw *rawRegistry, scheme string, item linkParam) string {
	if item.param.DropAlways {
		return ""
	}
	var parts []string
	seen := map[string]bool{}
	for _, path := range item.bodyPaths {
		f, _ := resolveBodyField(raw, scheme, path)
		if f == nil {
			continue
		}
		// Запрет живёт на БЛОКЕ, а параметр ссылки целится в поле внутри него:
		// `fp` кладёт значение в tls.utls.fingerprint, а forbidden_for стоит
		// на tls.utls. Без подъёма по пути страница hysteria2 продолжала бы
		// обещать, что отпечаток применится, — ровно та ложь, из-за которой
		// правило и переехало в реестр.
		if banned := forbiddenAncestor(raw, scheme, path); banned != nil {
			f = banned
		}
		for _, o := range fieldOutcomes(f, scheme, "../") {
			if seen[o] {
				continue
			}
			seen[o] = true
			parts = append(parts, o)
		}
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, " · ")
}

// renderBodyList — поля тела списком, в порядке body.order. Ссылочные поля
// (`ref`) разворачиваются не здесь, а ниже, в разделе диагностируемых
// проблем: тут достаточно строки со ссылкой на общую страницу.
func renderBodyList(b *strings.Builder, scheme string, body *registry.BodySchema, groups []linkGroup) {
	b.WriteString("## Body fields\n\n")
	if body == nil {
		b.WriteString("No body schema in the registry.\n\n")
		return
	}
	if len(groups) > 0 {
		b.WriteString("The node body itself — the sing-box JSON kept in the launcher state. " +
			"The path is the one used in that body, and the rules below apply to every input " +
			"alike: a share link, sing-box JSON, Xray JSON or a hand-filled form.\n\n")
	} else {
		b.WriteString("The node body itself — the sing-box JSON kept in the launcher state. " +
			"The path is the one used in that body.\n\n")
	}
	l := &list{b: b, byPath: linkParamsByBodyPath(groups), anchors: true, scheme: scheme}
	for _, name := range body.Order {
		f := body.Fields[name]
		if f == nil {
			continue
		}
		// Ссылочное поле (tls, transport, multiplex, dialer) РАЗВОРАЧИВАЕТСЯ
		// здесь целиком, а не сводится к строке «см. общую страницу». Словарь
		// ссылки выше по странице кладёт значения именно в эти поля и ссылается
		// на них якорем; страница, обещающая адрес, которого на ней нет, — та
		// же беда, из-за которой общие параметры ссылки и переехали сюда.
		// Общая страница остаётся справочником и названа строкой ниже.
		if file, ok := refPage(name, f); ok {
			l.item(anchorTag(bodyAnchor(name))+"**`"+name+"`**", f.DescEn)
			l.attr("Shared sub-schema, expanded below · reference page: [" +
				strings.TrimSuffix(file, ".md") + "](" + file + ")")
			writeChildren(l, name, f, "../")
			continue
		}
		writeBodyItems(l, "", name, f, "../")
	}
	b.WriteString("\n")
}

// writeBodyItems печатает поле и, для вложенных объектов и вариантов, его
// потомков отдельными пунктами с полным путём.
func writeBodyItems(l *list, prefix, name string, f *registry.Field, linkPrefix string) {
	path := name
	if prefix != "" {
		path = prefix + "." + name
	}
	head := "**`" + path + "`**"
	if l.anchors {
		head = anchorTag(bodyAnchor(path)) + head
	}
	l.item(head, f.DescEn)

	// Тип, ограничения значения.
	l.attr(strings.Join(nonEmpty(bodyType(f), bodyConstraints(f)), ", "))

	// Дефолт и обязательность. «Default: none · Required: yes» — шум: у
	// обязательного поля дефолта не бывает по определению, достаточно сказать,
	// что оно обязательное.
	if s := scalar(f.Default); s != "" {
		l.attr("Default: " + s)
	}
	if f.Required {
		l.attr("Required: the node is dropped without it")
	}

	// Кто кладёт сюда значение из ссылки.
	if names := l.setByLink(path); names != "" {
		l.attr("Set by link parameter: " + names)
	}

	// Что случится с негодным значением. Внутри запрещённого блока — ничего:
	// строку о запрете уже напечатал сам блок.
	if !l.banned {
		for _, o := range fieldOutcomes(f, l.scheme, linkPrefix) {
			l.attr(o)
		}
	}
	// Связи с другими полями. `forbidden_for`/`allowed_for` на странице ОДНОЙ
	// схемы не печатаются: страница уже про неё, и перечень чужих схем здесь
	// только шум (поле, запрещённое самой этой схеме, на странице и так стоит
	// как снятое — см. раздел Diagnosed problems).
	for _, r := range fieldRelations(f, l.scheme == "") {
		l.attr(r)
	}
	if g := bodyGate(f); g != "" {
		l.attr(g)
	}
	for _, g := range bodyCoreGate(f) {
		l.attr(g)
	}

	// Потомки запрещённого блока печатаются без своих правил: флаг снимается
	// после обхода, чтобы соседний разрешённый блок его не унаследовал.
	wasBanned := l.banned
	if !wasBanned && l.scheme != "" && !fieldAllowedFor(f, l.scheme) {
		l.banned = true
	}
	writeChildren(l, path, f, linkPrefix)
	l.banned = wasBanned
}

// writeChildren печатает потомков поля — варианты и вложенные объекты — с
// полным путём, не повторяя само поле. Вынесено из writeBodyItems, потому что
// разрешённое ссылочное поле (tls, transport) печатается по-своему, а
// разворачивается так же.
func writeChildren(l *list, path string, f *registry.Field, linkPrefix string) {
	if len(f.Variants) > 0 {
		names := make([]string, 0, len(f.Variants))
		for v := range f.Variants {
			names = append(names, v)
		}
		sort.Strings(names)
		for _, v := range names {
			writeNested(l, path+"."+v, f.Variants[v], linkPrefix)
		}
		return
	}
	writeNested(l, path, f, linkPrefix)
}

func writeNested(l *list, path string, f *registry.Field, linkPrefix string) {
	inner := f
	if len(inner.Fields) == 0 && inner.Items != nil {
		inner = inner.Items
	}
	if len(inner.Fields) == 0 {
		return
	}
	order := inner.Order
	if len(order) == 0 {
		for k := range inner.Fields {
			order = append(order, k)
		}
		sort.Strings(order)
	}
	for _, name := range order {
		child := inner.Fields[name]
		if child == nil {
			continue
		}
		writeBodyItems(l, path, name, child, linkPrefix)
	}
}

// fieldOutcomes — что санитайзер делает со значением: действие плюс код.
func fieldOutcomes(f *registry.Field, scheme, linkPrefix string) []string {
	// Поле, запрещённое ЭТОЙ схеме, до тела не доедет: правила его значения
	// здесь не работают, и печатать их — обещать диагностику, которой не
	// будет. Вместо них одна строка о запрете с кодом, который реально
	// поставит санитайзер (у QUIC он свой — tls_not_applicable_quic).
	// На общих страницах суб-схем (scheme == "") запрета «этой схеме» нет:
	// там перечень схем печатает fieldRelations.
	if scheme != "" && !fieldAllowedFor(f, scheme) {
		return []string{"Not applicable to `" + scheme + "`: removed → " +
			warnLink(forbiddenCode(f, scheme), linkPrefix)}
	}
	var out []string
	if f.OnInvalid != nil {
		out = append(out, "If invalid: "+onInvalidAction(f.OnInvalid)+" → "+
			warnLink(f.OnInvalid.Code, linkPrefix))
	}
	for _, a := range f.Advisory {
		desc := "Accepted with a notice for " + scalarList(a.Values)
		if len(a.Except) > 0 {
			desc = "Accepted with a notice for anything except " + scalarList(a.Except)
		}
		if a.When != nil && a.When.Path != "" {
			desc += ", when `" + a.When.Path + "` is set"
		}
		out = append(out, desc+" → "+warnLink(a.Code, linkPrefix))
	}
	if dw := f.DefaultWhen; dw != nil && dw.Absent {
		line := "If absent: filled in with " + scalar(dw.Value) + conditionPhrase(dw.When)
		if dw.Code != "" {
			line += " → " + warnLink(dw.Code, linkPrefix)
		}
		out = append(out, line)
	}
	if mw := f.MaxWhen; mw != nil {
		out = append(out, maxWhenPhrase(mw, linkPrefix))
	}
	if cw := f.CoerceWhen; cw != nil {
		out = append(out, "Replaced: "+scalarList(cw.Values)+" → "+scalar(cw.Value)+conditionPhrase(cw.When)+
			" → "+warnLink(cw.Code, linkPrefix))
	}
	if fi := f.ItemForbidden; fi != nil {
		out = append(out, "Items not accepted: "+scalarList(fi.Values)+" — removed, the rest stay → "+
			warnLink(fi.Code, linkPrefix))
	}
	if f.NormalizeCode != "" {
		out = append(out, "If the value had to be cleaned up: "+warnLink(f.NormalizeCode, linkPrefix))
	}
	if f.DropAlways {
		out = append(out, "Always dropped")
	}
	return out
}

// fieldRelations — связи поля со схемой и с другими полями. withSchemes
// включает перечень схем: он нужен только там, где страница не про одну схему.
func fieldRelations(f *registry.Field, withSchemes bool) []string {
	var out []string
	if withSchemes && len(f.ForbiddenFor) > 0 {
		out = append(out, "Not supported by: "+codeList(f.ForbiddenFor))
	}
	if withSchemes && len(f.AllowedFor) > 0 {
		out = append(out, "Only for: "+codeList(f.AllowedFor))
	}
	for _, c := range f.Conflicts {
		out = append(out, "Conflicts with: "+code(c.With)+unlessPhrase(c))
	}
	for _, rq := range f.Requires {
		if rq.Set != nil {
			out = append(out, "Requires: "+code(rq.Path)+unlessPhrase(rq)+" — if missing, filled in with "+scalar(rq.Set))
			continue
		}
		req := "Meaningless without: " + code(rq.Path)
		if rq.Equals != nil {
			req += " = " + scalar(rq.Equals)
		}
		req += unlessPhrase(rq)
		out = append(out, req)
	}
	if oh := f.OnHopRequired; oh != nil {
		out = append(out, "Not stripped when a hop at position 2 or later requires this path ("+code(oh.Code)+")")
	}
	return out
}

// unlessPhrase — хвост «unless … is set» для связи с Relation.UnlessSet.
func unlessPhrase(r registry.Relation) string {
	// Условие действия связи (`when`, контракт 1.1.56) — часть правила:
	// «conflicts with `vhttp`» без «when `vhttp` is h3» читалось бы как
	// запрет поля при любом vhttp.
	out := conditionPhrase(r.When)
	if len(r.UnlessSet) == 0 {
		return out
	}
	return out + " (unless " + codeList(r.UnlessSet) + " is set)"
}

func bodyType(f *registry.Field) string {
	typ := f.Type
	if f.Discriminator != "" {
		typ += " (variants by `" + f.Discriminator + "`)"
	}
	if f.Tristate {
		typ += ", tristate"
	}
	if f.Secret {
		typ += ", secret"
	}
	if f.Role != "" {
		typ += ", role `" + f.Role + "`"
	}
	if f.Deprecated {
		typ += ", deprecated"
	}
	if f.Managed {
		typ += ", set by config build"
	}
	if f.AllOrNothing {
		// Формулировка описывает ПОВЕДЕНИЕ ЯДРА, а не действие конвейера:
		// дефолты соседей не дописываются, частичная секция едет как есть
		// (SPEC 131 DRIFT §7.20).
		typ += ", all-or-nothing in the core (setting one field leaves the " +
			"neighbours at zero, i.e. unlimited; a partly filled section is " +
			"passed through unchanged)"
	}
	if typ == "" {
		return ""
	}
	return "Type: " + typ
}

func bodyConstraints(f *registry.Field) string {
	var parts []string
	if len(f.Values) > 0 {
		parts = append(parts, scalarList(f.Values))
	}
	if f.Format != "" {
		parts = append(parts, "format "+code(f.Format))
	}
	if f.Pattern != "" {
		parts = append(parts, "must match "+code(f.Pattern))
	}
	if len(f.AbsentValues) > 0 {
		parts = append(parts, "means \"not set\": "+scalarList(f.AbsentValues))
	}
	if len(f.AbsentWhen) > 0 {
		// Объект, объявленный незаданным, снимается ЦЕЛИКОМ и молча, до
		// правил своих полей и до связей соседей (PARSING_PRINCIPLES §6.1). Сказать это
		// в документации важнее, чем перечислить ключи: человек читает
		// страницу поля и должен понимать, почему блок исчезает без кода.
		parts = append(parts, "dropped entirely and silently when "+
			absentWhenList(f.AbsentWhen)+" (the object then counts as \"not set\" "+
			"for every presence check)")
	}
	if f.Min != nil || f.Max != nil {
		lo, hi := "…", "…"
		if f.Min != nil {
			lo = trimFloat(*f.Min)
		}
		if f.Max != nil {
			hi = trimFloat(*f.Max)
		}
		parts = append(parts, code(lo+"–"+hi))
	}
	if f.Len != nil {
		parts = append(parts, "len "+code(strconv.Itoa(*f.Len)))
	}
	if f.LenParity != "" {
		parts = append(parts, "len "+code(f.LenParity))
	}
	if f.Normalize != "" {
		parts = append(parts, "normalized: "+code(f.Normalize))
	}
	if f.Skip != "" {
		parts = append(parts, "not written by the launcher")
	}
	return strings.Join(parts, ", ")
}

func bodyGate(f *registry.Field) string {
	var parts []string
	if f.MinCore != "" {
		parts = append(parts, "core ≥ "+code(f.MinCore))
	}
	if f.LxOnly {
		parts = append(parts, "lx fork only")
	}
	if f.BuildTag != "" {
		parts = append(parts, "build tag "+code(f.BuildTag))
	}
	if f.Platform != "" {
		parts = append(parts, "OS "+code(f.Platform))
	}
	if len(parts) == 0 {
		return ""
	}
	return "Only written when: " + strings.Join(parts, ", ")
}

// bodyCoreGate — узловой гейт ядра и уровень протокола у поля (контракт
// 1.1.60): `on_core_unsupported`, `range_form`, `level`/`level_mark`.
func bodyCoreGate(f *registry.Field) []string {
	var out []string
	if a := f.OnCoreUnsupported; a != nil {
		out = append(out, "On a core that lacks it the whole node is dropped at build: "+code(a.Code))
	}
	if rf := f.RangeForm; rf != nil {
		var parts []string
		if rf.MinCore != "" {
			parts = append(parts, "core ≥ "+code(rf.MinCore))
		}
		if rf.BuildTag != "" {
			parts = append(parts, "build tag "+code(rf.BuildTag))
		}
		line := "Range form `N-M`"
		if len(parts) > 0 {
			line += " needs " + strings.Join(parts, ", ")
		}
		if rf.Level != "" {
			line += "; means level " + code(rf.Level)
		}
		if a := rf.OnCoreUnsupported; a != nil {
			line += "; on a core that lacks it the whole node is dropped at build: " + code(a.Code)
		}
		if len(parts) > 0 && rf.BuildTag != "" {
			line += "; removing the extension collapses the range to its lower bound"
		}
		out = append(out, line)
	}
	if f.Level != "" {
		line := "Means protocol level " + code(f.Level)
		if f.LevelMark != "" {
			line += ", adds " + code(f.LevelMark) + " to the level label"
		}
		out = append(out, line)
	}
	return out
}

// refPage говорит, есть ли у ссылочного поля собственная страница.
// Разрешённое поле теряет исходный `ref`, поэтому суб-схема узнаётся по форме:
// вариантный узел — транспорты, объект с полями — по имени поля.
func refPage(name string, f *registry.Field) (string, bool) {
	if len(f.Variants) > 0 {
		return subPageFile["transports"], true
	}
	if f.Type != "object" || len(f.Fields) == 0 {
		return "", false
	}
	if file, ok := subPageFile[name]; ok {
		return file, true
	}
	return "", false
}

func nonEmpty(items ...string) []string {
	out := make([]string, 0, len(items))
	for _, s := range items {
		if strings.TrimSpace(s) != "" {
			out = append(out, s)
		}
	}
	return out
}

func trimFloat(v float64) string {
	if v == float64(int64(v)) {
		return strconv.FormatInt(int64(v), 10)
	}
	return strconv.FormatFloat(v, 'g', -1, 64)
}
