package main

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"singbox-launcher/contract"
	"singbox-launcher/core/config/registry"
)

// subPage — страница общей суб-схемы (tls / transports / multiplex / dialer).
// Схема протокола ссылается на неё строкой «tls → см. _tls.md», а правила
// лежат здесь в одном экземпляре.
//
// Страница английская целиком, как и страницы схем (решение владельца):
// `desc_ru` и `impl` в неё не попадают, широких таблиц нет — поля идут
// списком, как на странице схемы.
type subPage struct {
	file  string
	title string
	body  string
}

func (s *subPage) render() string { return s.body }

func subSchemaPages(raw *rawRegistry) []*subPage {
	names := []string{"dialer", "multiplex", "tls", "transports"}
	out := make([]*subPage, 0, len(names))
	for _, name := range names {
		page, err := renderSubSchema(raw, name)
		if err != nil {
			// Суб-схема обязана читаться: без неё не собирается ни одна схема.
			panic(fmt.Sprintf("gendocs: %s: %v", name, err))
		}
		out = append(out, page)
	}
	return out
}

// subFile — секции суб-схемы, как они лежат на диске. Загрузчик лаунчера
// отдаёт суб-схемы только уже разрешёнными внутрь схемы протокола (у него нет
// и не должно быть публичного «дай мне tls.json целиком»), поэтому для
// отдельной страницы файл читается здесь напрямую — теми же структурами
// registry.Field, то есть без второго словаря атрибутов.
type subFile struct {
	Body struct {
		Core          string                        `json:"core"`
		Order         []string                      `json:"order"`
		Fields        map[string]*registry.Field    `json:"fields"`
		AbsentWhen    map[string]interface{}        `json:"absent_when"`
		Skipped       map[string]string             `json:"skipped"`
		DescEn        string                        `json:"desc_en"`
		Discriminator string                        `json:"discriminator"`
		Values        []string                      `json:"values"`
		Variants      map[string]*subVariantSection `json:"variants"`
	} `json:"body"`
	Common *struct {
		Core   string                     `json:"core"`
		Order  []string                   `json:"order"`
		Fields map[string]*registry.Field `json:"fields"`
	} `json:"common"`
	DescEn string `json:"desc_en"`
}

type subVariantSection struct {
	Order    []string                   `json:"order"`
	Fields   map[string]*registry.Field `json:"fields"`
	LxOnly   bool                       `json:"lx_only"`
	MinCore  string                     `json:"min_core"`
	BuildTag string                     `json:"build_tag"`
	DescEn   string                     `json:"desc_en"`
}

func renderSubSchema(raw *rawRegistry, name string) (*subPage, error) {
	data, err := contract.ReadRegistry(name + ".json")
	if err != nil {
		return nil, err
	}
	var f subFile
	if err := json.Unmarshal(data, &f); err != nil {
		return nil, err
	}

	var b strings.Builder
	b.WriteString("# " + name + "\n\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("A shared registry sub-schema (`contract/registry/" + name + ".json`): its " +
		"fields are substituted into the body of every scheme that refers to it.\n\n")
	b.WriteString("[← index](../index.md) · [diagnosed problems](../warnings.md)\n\n")
	if f.Body.Core != "" {
		b.WriteString("Core the schema was checked against: `" + f.Body.Core + "`\n\n")
	}
	if len(f.Body.AbsentWhen) > 0 {
		// Условие «секции нет» объявлено у самой суб-схемы и переезжает в
		// каждое поле, которое её подключает, — поэтому и на странице оно
		// стоит в шапке, а не у отдельного поля.
		b.WriteString("**The whole block is dropped entirely and silently when " +
			absentWhenList(f.Body.AbsentWhen) + "** — that is how the core reads it " +
			"(\"not configured\", not \"configured and switched off\"). The block is then " +
			"absent for every presence check, including its own nested blocks.\n\n")
	}
	if d := mdText(f.DescEn); d != "" {
		b.WriteString("> " + d + "\n\n")
	}

	// Параметры ссылки, если суб-схема их несёт (tls, transports).
	renderSubURI(&b, raw, name)

	if f.Common != nil {
		b.WriteString("## Common fields\n\n")
		l := &list{b: &b, anchors: true}
		writeSection(l, f.Common.Order, f.Common.Fields)
		b.WriteString("\n")
	}

	if len(f.Body.Variants) > 0 {
		b.WriteString("## Variants\n\n")
		b.WriteString("Discriminator: `" + f.Body.Discriminator + "` — " +
			codeList(f.Body.Values) + "\n\n")
		if d := mdText(f.Body.DescEn); d != "" {
			b.WriteString("> " + d + "\n\n")
		}
		vnames := make([]string, 0, len(f.Body.Variants))
		for v := range f.Body.Variants {
			vnames = append(vnames, v)
		}
		sort.Strings(vnames)
		for _, v := range vnames {
			variant := f.Body.Variants[v]
			b.WriteString("### `" + v + "`\n\n")
			if gate := variantGate(variant); gate != "" {
				b.WriteString(gate + "\n\n")
			}
			if d := mdText(variant.DescEn); d != "" {
				b.WriteString("> " + d + "\n\n")
			}
			l := &list{b: &b, anchors: true}
			// Имя варианта — часть пути: словарь кодов адресует поле как
			// `xhttp.xmux.max_concurrency`, и страница обязана звать его так
			// же, иначе ссылка из warnings.md ведёт в никуда.
			writeSectionUnder(l, v, variant.Order, variant.Fields)
			b.WriteString("\n")
		}
	} else if len(f.Body.Fields) > 0 {
		b.WriteString("## Body fields\n\n")
		if d := mdText(f.Body.DescEn); d != "" {
			b.WriteString("> " + d + "\n\n")
		}
		l := &list{b: &b, anchors: true}
		writeSection(l, f.Body.Order, f.Body.Fields)
		b.WriteString("\n")
	}

	if len(f.Body.Skipped) > 0 {
		b.WriteString("## Deliberately not described\n\n")
		keys := make([]string, 0, len(f.Body.Skipped))
		for k := range f.Body.Skipped {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		l := &list{b: &b}
		for _, k := range keys {
			l.item(code(k), f.Body.Skipped[k])
		}
		b.WriteString("\n")
	}

	return &subPage{file: subPageFile[name], title: name, body: b.String()}, nil
}

// writeSection печатает поля секции списком — тем же видом, что и на странице
// схемы, чтобы одно и то же поле выглядело одинаково в обоих местах.
func writeSection(l *list, order []string, fields map[string]*registry.Field) {
	writeSectionUnder(l, "", order, fields)
}

// writeSectionUnder — то же, но с префиксом пути: у вариантной суб-схемы имя
// варианта входит в путь поля.
func writeSectionUnder(l *list, prefix string, order []string, fields map[string]*registry.Field) {
	if len(order) == 0 {
		for k := range fields {
			order = append(order, k)
		}
		sort.Strings(order)
	}
	for _, name := range order {
		f := fields[name]
		if f == nil {
			continue
		}
		writeBodyItems(l, prefix, name, f, "../")
	}
}

func variantGate(v *subVariantSection) string {
	var parts []string
	if v.MinCore != "" {
		parts = append(parts, "core ≥ `"+v.MinCore+"`")
	}
	if v.LxOnly {
		parts = append(parts, "lx fork only")
	}
	if v.BuildTag != "" {
		parts = append(parts, "build tag `"+v.BuildTag+"`")
	}
	if len(parts) == 0 {
		return ""
	}
	return "**" + strings.Join(parts, " · ") + "**"
}

// renderSubURI печатает параметры ссылки, которые лежат в суб-схеме: TLS и
// REALITY у tls.json, семейства транспортов у transports.json.
//
// Эти же параметры печатаются и на странице каждой схемы, которая их носит —
// там они вдобавок знают правило поля тела и применимость. Здесь они собраны
// в одном месте как справочник: один экземпляр, без схемы вокруг.
func renderSubURI(b *strings.Builder, raw *rawRegistry, name string) {
	switch name {
	case "tls":
		b.WriteString("## Link parameters\n\n")
		b.WriteString("These are repeated on the page of every scheme that carries a TLS " +
			"block, together with the rule of the body field each one maps to.\n\n")
		l := &list{b: b}
		for _, k := range raw.tlsOrder {
			if p := raw.tlsParams[k]; p != nil {
				writeSubURIItem(l, k, p)
			}
		}
		for _, k := range raw.realityOrder {
			if p := raw.realityParams[k]; p != nil {
				writeSubURIItem(l, k, p)
			}
		}
		b.WriteString("\n")
	case "transports":
		b.WriteString("## Link parameters\n\n")
		b.WriteString("These are repeated on the page of every scheme that carries a " +
			"transport block, together with the rule of the body field each one maps to. " +
			"The body path below is written relative to the transport block: in a node " +
			"body the variant is a segment of its own, e.g. `transport.ws.path`.\n\n")
		for _, tname := range raw.transportOrder {
			tr := raw.transports[tname]
			if tr == nil {
				continue
			}
			head := "### `" + tname + "`"
			if tr.SingboxType != "" && tr.SingboxType != tname {
				head += " → `" + tr.SingboxType + "`"
			}
			b.WriteString(head + "\n\n")
			l := &list{b: b}
			for _, k := range tr.paramOrder {
				if p := tr.Params[k]; p != nil {
					writeSubURIItem(l, k, p)
				}
			}
			b.WriteString("\n")
		}
	}
}

// writeSubURIItem — параметр ссылки на странице общей суб-схемы. Правила поля
// тела здесь нет и быть не может: одно и то же поле у разных схем живёт по
// разным правилам (`fp` запрещён naive), а суб-схема не знает, о какой схеме
// речь. За правилом — на страницу схемы.
func writeSubURIItem(l *list, name string, p *uriParam) {
	l.item("**`"+name+"`**", p.DescEn)
	if p.Ext != "" {
		l.attr(extWord(p.Ext))
	}
	writeParamAttrs(l, p)
	if p.DropAlways {
		l.attr("Maps to: nothing — the parameter is read and then deliberately dropped")
		return
	}
	if paths := p.mapsToPaths(); len(paths) > 0 {
		l.attr("Maps to: " + codeList(paths))
	}
}
