package main

import (
	"encoding/json"
	"sort"
	"strings"

	"singbox-launcher/contract"
	"singbox-launcher/core/config/registry"
)

// usage — одно место, где код может возникнуть: схема (или суб-схема) и путь
// поля. Собирается обходом всех body-секций реестра.
type usage struct {
	scheme string
	path   string
	via    string // on_invalid | advisory | conflicts | requires | allowed_for/forbidden_for
	// action — что происходит с полем или узлом: «removed», «replaced with
	// chrome», «node dropped», «kept with a notice». Без него список путей
	// говорит, ГДЕ код возникает, но не говорит, чем это кончится.
	action string
}

// renderWarnings строит warnings.md: по коду — якорь, severity, что
// произошло, почему это бывает, что с этим делать, и обратный индекс «где
// возникает».
//
// Страница английская целиком (решение владельца): русские тексты реестра
// (`title_ru`/`text_ru`/`cause_ru`/`fix_ru`) в неё не попадают — их читает UI,
// а не документация.
//
// Обратный индекс — единственное, чего в реестре нет в готовом виде: реестр
// хранит ссылку поле→код, а человеку нужна ссылка код→поля. Он собирается
// обходом body-секций всех файлов; код, на который не ссылается ни одно поле,
// помечается как код уровня узла/подписки.
func renderWarnings(raw *rawRegistry, reg *registry.Registry) string {
	index := buildUsageIndex()

	codes := warningCodes()
	var b strings.Builder
	b.WriteString("# Diagnosed problems (warning codes)\n\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("The `contract/registry/warnings.json` dictionary is shared with LxBox: both " +
		"apps report the same event under the same name.\n\n")
	b.WriteString("`severity: error` means the node was dropped; `warning` and `info` stay on a " +
		"surviving node.\n\n")
	b.WriteString("[← index](index.md)\n\n")

	b.WriteString("## Contents\n\n")
	for _, c := range codes {
		w, ok := reg.Warning(c)
		if !ok {
			continue
		}
		b.WriteString("- [`" + c + "`](#" + c + ") · `" + w.Severity + "` — " + mdText(w.TitleEn) + "\n")
	}
	b.WriteString("\n")

	for _, c := range codes {
		w, ok := reg.Warning(c)
		if !ok {
			continue
		}
		b.WriteString("<a id=\"" + c + "\"></a>\n")
		b.WriteString("### " + c + "\n\n")
		b.WriteString("**severity:** `" + w.Severity + "`")
		if len(w.Params) > 0 {
			b.WriteString(" · **params:** " + codeList(w.Params))
		}
		b.WriteString("\n\n")
		if w.TitleEn != "" {
			b.WriteString("**" + mdText(w.TitleEn) + "**\n\n")
		}
		writeAdvice(&b, w)
		writeUsages(&b, index[c])
	}
	return b.String()
}

// writeAdvice печатает три вопроса, на которые человеку нужен ответ: что
// случилось, почему так бывает и что с этим делать.
func writeAdvice(b *strings.Builder, w *registry.WarningEntry) {
	if t := mdText(w.TextEn); t != "" {
		b.WriteString("- **What happened:** " + t + "\n")
	}
	if c := mdText(w.CauseEn); c != "" {
		b.WriteString("- **Why it happens:** " + c + "\n")
	}
	if len(w.FixEn) > 0 {
		b.WriteString("- **What you can do:**\n")
		for _, f := range w.FixEn {
			if f = mdText(f); f != "" {
				b.WriteString("  - " + f + "\n")
			}
		}
	}
	b.WriteString("\n")
}

func writeUsages(b *strings.Builder, list []usage) {
	b.WriteString("**Where it comes from:**\n\n")
	if len(list) == 0 {
		b.WriteString("- Node or subscription level: no field in the registry points at this " +
			"code, so it is raised while the entry as a whole is being read.\n\n")
		return
	}
	// Группировка по схеме: человек читает страницу протокола и ищет свою
	// схему, а не перебирает шестнадцать строк подряд.
	order := make([]string, 0, len(list))
	byScheme := map[string][]usage{}
	for _, u := range list {
		if _, ok := byScheme[u.scheme]; !ok {
			order = append(order, u.scheme)
		}
		byScheme[u.scheme] = append(byScheme[u.scheme], u)
	}
	sort.Strings(order)
	for _, scheme := range order {
		b.WriteString("- " + schemeRef(scheme) + "\n")
		for _, u := range byScheme[scheme] {
			// Путь — ссылкой прямо на поле нужной страницы: со словаря кодов
			// человек идёт чинить конкретное поле, а не искать его глазами.
			line := "[`" + u.path + "`](" + schemeFieldLink(scheme, u.path) + ") — " + u.via
			if u.action != "" {
				line += " → " + u.action
			}
			b.WriteString("  - " + mdText(line) + "\n")
		}
	}
	b.WriteString("\n")
}

// schemeRef — ссылка на страницу схемы либо на общую суб-схему.
func schemeRef(scheme string) string {
	return "[`" + scheme + "`](" + schemePageLink(scheme) + ")"
}

func schemePageLink(scheme string) string {
	if file, ok := subPageFile[scheme]; ok {
		return "protocols/" + file
	}
	return "protocols/" + schemeFileName(scheme)
}

// schemeFieldLink — ссылка на конкретное поле нужной страницы. Пути в
// обратном индексе записаны так же, как их печатает страница: у суб-схемы —
// относительно неё самой (`reality.public_key`), у схемы — от корня тела.
func schemeFieldLink(scheme, path string) string {
	return schemePageLink(scheme) + "#" + bodyAnchor(path)
}

// buildUsageIndex обходит body-секции всех файлов реестра и собирает, какое
// поле на какой код ссылается. Обход идёт по сырым файлам, а не по
// разрешённой схеме: иначе поле суб-схемы попало бы в индекс 16 раз — по разу
// на каждую схему, которая её подставляет.
func buildUsageIndex() map[string][]usage {
	out := map[string][]usage{}

	files := []string{"tls.json", "transports.json", "multiplex.json", "dialer.json"}
	entries, err := contract.Registry.ReadDir("registry/protocols")
	if err == nil {
		names := make([]string, 0, len(entries))
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".json") {
				names = append(names, "protocols/"+e.Name())
			}
		}
		sort.Strings(names)
		files = append(files, names...)
	}
	sort.Strings(files)

	for _, name := range files {
		data, err := contract.ReadRegistry(name)
		if err != nil {
			continue
		}
		var f struct {
			Body   *rawSection `json:"body"`
			Common *rawSection `json:"common"`
		}
		if err := json.Unmarshal(data, &f); err != nil {
			continue
		}
		scheme := strings.TrimSuffix(strings.TrimPrefix(name, "protocols/"), ".json")
		// Суб-схема на странице зовётся своим именем (tls, transports, …),
		// а не именем файла.
		scheme = strings.TrimSuffix(scheme, ".json")
		for _, sec := range []*rawSection{f.Body, f.Common} {
			if sec == nil {
				continue
			}
			walkSection(out, scheme, "", sec)
		}
	}

	for c := range out {
		list := out[c]
		sort.SliceStable(list, func(i, j int) bool {
			if list[i].scheme != list[j].scheme {
				return list[i].scheme < list[j].scheme
			}
			if list[i].path != list[j].path {
				return list[i].path < list[j].path
			}
			return list[i].via < list[j].via
		})
		out[c] = list
	}
	return out
}

type rawSection struct {
	Order    []string                   `json:"order"`
	Fields   map[string]*registry.Field `json:"fields"`
	Variants map[string]*rawSection     `json:"variants"`
}

func walkSection(out map[string][]usage, scheme, prefix string, sec *rawSection) {
	names := sec.Order
	if len(names) == 0 {
		for k := range sec.Fields {
			names = append(names, k)
		}
		sort.Strings(names)
	}
	for _, name := range names {
		if f := sec.Fields[name]; f != nil {
			walkField(out, scheme, joinPath(prefix, name), f)
		}
	}
	vnames := make([]string, 0, len(sec.Variants))
	for v := range sec.Variants {
		vnames = append(vnames, v)
	}
	sort.Strings(vnames)
	for _, v := range vnames {
		walkSection(out, scheme, joinPath(prefix, v), sec.Variants[v])
	}
}

func walkField(out map[string][]usage, scheme, path string, f *registry.Field) {
	add := func(code, via, action string) {
		if code == "" {
			return
		}
		out[code] = append(out[code], usage{scheme: scheme, path: path, via: via, action: action})
	}
	if f.OnInvalid != nil {
		add(f.OnInvalid.Code, "the value does not fit the field", onInvalidAction(f.OnInvalid))
		if f.OnInvalid.ElseCode != "" {
			add(f.OnInvalid.ElseCode, "an object arrived without a usable `"+f.OnInvalid.Key+"` member", actionRemoved)
		}
	}
	for _, a := range f.Advisory {
		if len(a.Except) > 0 {
			add(a.Code, "the value is anything except "+scalarList(a.Except), actionKept)
			continue
		}
		add(a.Code, "the value is "+scalarList(a.Values), actionKept)
	}
	if dw := f.DefaultWhen; dw != nil && dw.Absent && dw.Code != "" {
		add(dw.Code, "the field is absent", "filled in with "+scalar(dw.Value))
	}
	if mw := f.MaxWhen; mw != nil {
		add(mw.Code, "the value is above "+scalar(mw.Max)+conditionPhrase(mw.When),
			"replaced with "+scalar(mw.Max))
		if mw.NoteCode != "" {
			add(mw.NoteCode, "the value is above "+scalar(mw.Max)+conditionPhrase(mw.When)+
				", but the body came from "+codeList(mw.ExceptSources), actionKept)
		}
	}
	if f.NormalizeCode != "" {
		add(f.NormalizeCode, "the value had to be cleaned up ("+f.Normalize+")", "value cleaned up")
	}
	for _, c := range f.Conflicts {
		add(c.Code, "conflicts with `"+c.With+"`"+unlessPhrase(c), actionRemoved)
	}
	for _, rq := range f.Requires {
		if rq.Set != nil {
			add(rq.Code, "set without `"+rq.Path+"`"+unlessPhrase(rq), "`"+rq.Path+"` filled in with "+scalar(rq.Set))
			continue
		}
		add(rq.Code, "set without `"+rq.Path+"`"+unlessPhrase(rq), actionRemoved)
	}
	if cw := f.CoerceWhen; cw != nil {
		add(cw.Code, "the value is "+scalarList(cw.Values)+conditionPhrase(cw.When), "replaced with "+scalar(cw.Value))
	}
	if oh := f.OnHopRequired; oh != nil {
		add(oh.Code, "a hop at position 2 or later requires this path", "not stripped")
	}
	if fi := f.ItemForbidden; fi != nil {
		add(fi.Code, "a list item is "+scalarList(fi.Values), "item removed")
	}
	if len(f.ForbiddenFor) > 0 {
		add(f.Code, "not supported by "+codeList(f.ForbiddenFor), actionRemoved)
	} else if len(f.AllowedFor) > 0 {
		add(f.Code, "supported only by "+codeList(f.AllowedFor), actionRemoved)
	} else if f.Code != "" {
		add(f.Code, "the field is present", "")
	}
	if f.Required && f.OnInvalid == nil {
		add("field_missing", "required and missing", actionNodeDropped)
	}

	inner := f
	if len(inner.Fields) == 0 && inner.Items != nil {
		inner = inner.Items
	}
	if len(inner.Fields) > 0 {
		names := inner.Order
		if len(names) == 0 {
			for k := range inner.Fields {
				names = append(names, k)
			}
			sort.Strings(names)
		}
		for _, name := range names {
			if child := inner.Fields[name]; child != nil {
				walkField(out, scheme, joinPath(path, name), child)
			}
		}
	}
}

// Действия санитайзера — одним словарём, чтобы страница называла одно и то же
// одинаково.
const (
	actionRemoved     = "removed"
	actionNodeDropped = "node dropped"
	actionKept        = "kept with a notice"
)

func onInvalidAction(oi *registry.OnInvalid) string {
	switch oi.Action {
	case "drop":
		return actionRemoved
	case "drop_node":
		return actionNodeDropped
	case "coerce":
		return "replaced with " + scalar(oi.Value)
	case "unwrap":
		return "an object is replaced with its `" + oi.Key + "` member"
	}
	return oi.Action
}

func joinPath(prefix, name string) string {
	if prefix == "" {
		return name
	}
	return prefix + "." + name
}

// warningCodes — коды словаря в алфавитном порядке (в файле они лежат по
// смыслу, но для листания по якорям нужен предсказуемый список).
func warningCodes() []string {
	data, err := contract.ReadRegistry("warnings.json")
	if err != nil {
		return nil
	}
	var f struct {
		Warnings map[string]json.RawMessage `json:"warnings"`
	}
	if err := json.Unmarshal(data, &f); err != nil {
		return nil
	}
	out := make([]string, 0, len(f.Warnings))
	for k := range f.Warnings {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
